"""URL builder, version handling, and alias map for docs.lammps.org.

The LAMMPS documentation lives at https://docs.lammps.org/ under three
version branches:

- ``stable``  → ``https://docs.lammps.org/stable/``  (most recent stable)
- ``latest``  → ``https://docs.lammps.org/latest/``  (develop branch)
- ``release`` → ``https://docs.lammps.org/``         (current feature release)

Most styles do not have a 1-to-1 page; LAMMPS doc maintainers chose
specific page slugs that group related variants. ``PAGE_SLUGS`` encodes
the curated alias table; ``SHARED_WITH`` is the reverse map computed
at import time.
"""

from __future__ import annotations

from collections import defaultdict

from ._generated_slugs import EXTRACTED_HOWTO_TOPICS, EXTRACTED_PAGE_SLUGS

DOC_ROOT = "https://docs.lammps.org/"

VERSION_PREFIX: dict[str, str] = {
    "stable": "stable/",
    "latest": "latest/",
    "release": "",
}

DEFAULT_VERSION = "stable"

COMMAND_PAGE_SECTIONS: tuple[tuple[str, str], ...] = (
    ("Syntax", "argument layout"),
    ("Examples", "canonical usage"),
    ("Description", "behaviour and units"),
    ("Restrictions", "package and applicability"),
    ("Related commands", "alternatives and companions"),
    ("Default", "default keyword values"),
)

HOWTO_PAGE_SECTIONS: tuple[tuple[str, str], ...] = (
    ("Overview", "scope and motivation"),
    ("Detailed sections", "step-by-step (varies per page)"),
    ("Related", "cross-references"),
)

CATEGORY_INDEXES: dict[str, str] = {
    "all": "Commands",
    "fix": "Commands_fix",
    "compute": "Commands_compute",
    "pair_style": "Commands_pair",
    "bond_style": "Commands_bond",
    "angle_style": "Commands_bond",
    "dihedral_style": "Commands_bond",
    "improper_style": "Commands_bond",
    "dump": "Commands_dump",
    "kspace_style": "Commands_kspace",
    "atom_style": "Commands.html#atom-style",
    "region": "Commands.html#region",
}

KNOWN_CATEGORIES: tuple[str, ...] = (
    "command",
    "pair_style",
    "bond_style",
    "angle_style",
    "dihedral_style",
    "improper_style",
    "fix",
    "compute",
    "dump",
    "kspace_style",
    "atom_style",
    "region",
)

# Howto topic list. Re-scraped from Howto.html by
# scripts/update_lammps_slugs.py. Used for did_you_mean suggestions
# when a user passes an unknown howto name.
HOWTO_TOPICS: tuple[str, ...] = EXTRACTED_HOWTO_TOPICS

# Manual aliases for styles not enumerated by Sphinx index tables.
# These all share single doc pages: atom_style variants live on
# ``atom_style.html``, region variants on ``region.html``, the listed
# kspace solvers on ``kspace_style.html``, and the listed dump formats
# (``atom``, ``custom``, ``xyz``, ``dcd``, ``yaml``, ``cfg``, ``local``)
# on ``dump.html``. Other dump formats (``image``, ``movie``, ``netcdf``,
# ``h5md``, ``molfile``, ``vtk``) have dedicated pages and are picked
# up by the auto-extractor.
MANUAL_PAGE_SLUGS: dict[tuple[str, str], str] = {
    # atom styles share one page
    ("atom_style", "angle"): "atom_style",
    ("atom_style", "atomic"): "atom_style",
    ("atom_style", "bond"): "atom_style",
    ("atom_style", "charge"): "atom_style",
    ("atom_style", "dipole"): "atom_style",
    ("atom_style", "ellipsoid"): "atom_style",
    ("atom_style", "full"): "atom_style",
    ("atom_style", "hybrid"): "atom_style",
    ("atom_style", "molecular"): "atom_style",
    ("atom_style", "sphere"): "atom_style",
    # dump formats that share dump.html
    ("dump", "atom"): "dump",
    ("dump", "cfg"): "dump",
    ("dump", "custom"): "dump",
    ("dump", "dcd"): "dump",
    ("dump", "local"): "dump",
    ("dump", "xyz"): "dump",
    ("dump", "yaml"): "dump",
    # kspace solvers all share kspace_style.html
    ("kspace_style", "ewald"): "kspace_style",
    ("kspace_style", "ewald/disp"): "kspace_style",
    ("kspace_style", "msm"): "kspace_style",
    ("kspace_style", "msm/cg"): "kspace_style",
    ("kspace_style", "pppm"): "kspace_style",
    ("kspace_style", "pppm/cg"): "kspace_style",
    ("kspace_style", "pppm/disp"): "kspace_style",
    ("kspace_style", "pppm/disp/tip4p"): "kspace_style",
    ("kspace_style", "pppm/stagger"): "kspace_style",
    ("kspace_style", "pppm/tip4p"): "kspace_style",
    ("kspace_style", "scafacos"): "kspace_style",
    # region shapes share region.html
    ("region", "block"): "region",
    ("region", "cone"): "region",
    ("region", "cylinder"): "region",
    ("region", "intersect"): "region",
    ("region", "plane"): "region",
    ("region", "prism"): "region",
    ("region", "sphere"): "region",
    ("region", "union"): "region",
}


# Auto-extracted slugs (regenerated by scripts/update_lammps_slugs.py)
# come first so manual entries can override on conflict.
PAGE_SLUGS: dict[tuple[str, str], str] = {
    **EXTRACTED_PAGE_SLUGS,
    **MANUAL_PAGE_SLUGS,
}


def _build_shared_with() -> dict[str, list[tuple[str, str]]]:
    """Reverse the alias map: slug -> list of (kind, name) sharing it."""
    shared: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for (kind, name), slug in PAGE_SLUGS.items():
        shared[slug].append((kind, name))
    for slug in shared:
        shared[slug].sort()
    return dict(shared)


SHARED_WITH = _build_shared_with()


def _validate_version(version: str) -> None:
    if version not in VERSION_PREFIX:
        raise ValueError(
            f"unknown LAMMPS doc version {version!r}; "
            f"valid: {sorted(VERSION_PREFIX)}"
        )


def build_url(slug: str, version: str = DEFAULT_VERSION) -> str:
    """Build a docs.lammps.org URL for a doc page slug."""
    _validate_version(version)
    return f"{DOC_ROOT}{VERSION_PREFIX[version]}{slug}.html"


def doc_root_url(version: str = DEFAULT_VERSION) -> str:
    _validate_version(version)
    return f"{DOC_ROOT}{VERSION_PREFIX[version]}"


def _section_descriptors(layout: tuple[tuple[str, str], ...]) -> list[dict[str, str]]:
    return [{"name": n, "purpose": p} for n, p in layout]


def doc_map(version: str = DEFAULT_VERSION) -> dict:
    """Structural overview of docs.lammps.org for the requested version."""
    _validate_version(version)
    root = doc_root_url(version)
    return {
        "version": version,
        "available_versions": sorted(VERSION_PREFIX),
        "doc_root": root,
        "manual_toc": f"{root}Manual.html",
        "command_indexes": {
            label: f"{root}{slug}.html" if "#" not in slug else f"{root}{slug}"
            for label, slug in CATEGORY_INDEXES.items()
        },
        "howto_index": f"{root}Howto.html",
        "categories": list(KNOWN_CATEGORIES),
        "page_layout": {
            "command_page_sections": _section_descriptors(COMMAND_PAGE_SECTIONS),
            "howto_page_sections": _section_descriptors(HOWTO_PAGE_SECTIONS),
        },
        "guidance": (
            "Use this map to plan navigation. For specific names use "
            "get_command_doc / get_style_doc / get_howto_doc."
        ),
    }


def _did_you_mean(name: str, candidates: list[str], limit: int = 5) -> list[str]:
    """Cheap edit-distance suggestion. Pure-Python, no external deps."""
    name_l = name.lower()
    name_set = set(name_l)
    scored: list[tuple[float, str]] = []
    for cand in candidates:
        cand_l = cand.lower()
        if name_l == cand_l:
            scored.append((0.0, cand))
            continue
        cand_set = set(cand_l)
        intersection = len(name_set & cand_set)
        union = len(name_set | cand_set) or 1
        jaccard = intersection / union
        prefix_match = len(_common_prefix(name_l, cand_l))
        score = -(jaccard + 0.1 * prefix_match)
        scored.append((score, cand))
    scored.sort()
    return [c for _, c in scored[:limit]]


def _common_prefix(a: str, b: str) -> str:
    out: list[str] = []
    for ca, cb in zip(a, b):
        if ca != cb:
            break
        out.append(ca)
    return "".join(out)


def _command_index_url(category: str, version: str) -> str:
    root = doc_root_url(version)
    target = CATEGORY_INDEXES.get(category, "Commands")
    if "#" in target:
        return f"{root}{target}"
    return f"{root}{target}.html"


def _shared_with_dicts(slug: str, exclude: tuple[str, str]) -> list[dict[str, str]]:
    return [
        {"kind": k, "name": n}
        for (k, n) in SHARED_WITH.get(slug, ())
        if (k, n) != exclude
    ]


def command_url(name: str, version: str = DEFAULT_VERSION) -> dict:
    """Resolve a top-level command name."""
    _validate_version(version)
    key = ("command", name)
    if key in PAGE_SLUGS:
        slug = PAGE_SLUGS[key]
        url = build_url(slug, version)
        return {
            "name": name,
            "version": version,
            "candidates": [
                {
                    "url": url,
                    "slug": slug,
                    "shared_with": _shared_with_dicts(slug, key),
                    "confidence": "high",
                    "rationale": "exact alias-map hit",
                }
            ],
            "sections": _section_descriptors(COMMAND_PAGE_SECTIONS),
            "next_action": (
                f"Fetch the candidate URL and read the Syntax section to "
                f"verify usage of `{name}`."
            ),
        }
    candidates_by_name = [n for (k, n) in PAGE_SLUGS if k == "command"]
    return {
        "name": name,
        "version": version,
        "candidates": [],
        "did_you_mean": _did_you_mean(name, candidates_by_name),
        "fallback": {
            "url": _command_index_url("all", version),
            "rationale": (
                "Name not in alias map. The full LAMMPS command index "
                "is the LAMMPS-authoritative listing."
            ),
            "next_action": "Fetch the fallback URL and locate the command by name.",
        },
    }


def style_url(category: str, name: str, version: str = DEFAULT_VERSION) -> dict:
    """Resolve a style (fix npt, pair_style lj/cut, compute temp, ...)."""
    _validate_version(version)
    if category not in KNOWN_CATEGORIES:
        return {
            "category": category,
            "name": name,
            "version": version,
            "error": f"unknown category {category!r}",
            "valid_categories": list(KNOWN_CATEGORIES),
        }
    key = (category, name)
    if key in PAGE_SLUGS:
        slug = PAGE_SLUGS[key]
        url = build_url(slug, version)
        shared = _shared_with_dicts(slug, key)
        rationale = "exact alias-map hit"
        if shared:
            rationale = (
                f"shared page hosting {len(shared)} other style(s) in this category"
            )
        return {
            "category": category,
            "name": name,
            "version": version,
            "candidates": [
                {
                    "url": url,
                    "slug": slug,
                    "shared_with": shared,
                    "confidence": "high",
                    "rationale": rationale,
                }
            ],
            "sections": _section_descriptors(COMMAND_PAGE_SECTIONS),
            "next_action": (
                f"Fetch the candidate URL and read the Syntax section. "
                f"The page may cover multiple variants; locate the section "
                f"specific to `{category} {name}`."
            ),
        }
    candidates_by_name = [n for (k, n) in PAGE_SLUGS if k == category]
    return {
        "category": category,
        "name": name,
        "version": version,
        "candidates": [],
        "did_you_mean": _did_you_mean(name, candidates_by_name),
        "fallback": {
            "url": _command_index_url(category, version),
            "rationale": (
                f"Name not in alias map for category {category!r}. The "
                f"category index lists all known styles with their doc URLs."
            ),
            "next_action": "Fetch the fallback URL and locate the style by name.",
        },
    }


def howto_url(topic: str, version: str = DEFAULT_VERSION) -> dict:
    """Resolve a howto topic (Howto_<topic>.html)."""
    _validate_version(version)
    if topic in HOWTO_TOPICS:
        slug = f"Howto_{topic}"
        return {
            "topic": topic,
            "version": version,
            "url": build_url(slug, version),
            "slug": slug,
            "sections": _section_descriptors(HOWTO_PAGE_SECTIONS),
            "confidence": "high",
            "next_action": "Fetch the URL; howto pages vary in structure.",
        }
    return {
        "topic": topic,
        "version": version,
        "url": None,
        "did_you_mean": _did_you_mean(topic, list(HOWTO_TOPICS)),
        "fallback": {
            "url": f"{doc_root_url(version)}Howto.html",
            "rationale": (
                "Topic not in known howto list (might be added since the "
                "alias was last refreshed). Howto.html is the authoritative "
                "index."
            ),
            "next_action": "Fetch the howto index and look for the topic.",
        },
    }


def known_categories() -> tuple[str, ...]:
    return KNOWN_CATEGORIES
